FROM python:3.11-slim

WORKDIR /sqlmesh_project

# Dependências do sistema
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    python3-dev \
    libc6-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia e instala dependências Python
COPY sqlmesh_project/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# CMD padrão: shell interativo
CMD ["/bin/bash"]
